### ISSUE TITLE
Question: c/amo-set.c  about expected output

### ISSUE THREAD

**Issue by G3orge26** [openshmem-org/openshmem-examples#8]
Hello, 
I have been running the tests of openshmem on my local installation and I encountered the c/amo-set.c test.
The test states that the expected output of PE1 should be 999. According to openshmem memory model PE1 could possibly be either 999 or 1000. The lines [75](https://github.com/openshmem-org/openshmem-examples/blob/master/c/amo-set.c#L75) and [78](https://github.com/openshmem-org/openshmem-examples/blob/master/c/amo-set.c#L78) could be executed in any order, thus resulting in a scenario where PE0 first executes the set and PE1 increments dst afterwards resulting in 1000 instead of 999.

The first code block shows an execution with the expected values.
```
0: dst = 123
1: dst = 999
2: dst = 124
3: dst = 124
```

While this second one shows the indicated issue.
```
0: dst = 123
3: dst = 124
2: dst = 124
1: dst = 1000
```

**Comment by jdinan** [comment]
Please review #9
